// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: analytics.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на статистику по пользователю
type UserTaskStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTaskStatsRequest) Reset() {
	*x = UserTaskStatsRequest{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTaskStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTaskStatsRequest) ProtoMessage() {}

func (x *UserTaskStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTaskStatsRequest.ProtoReflect.Descriptor instead.
func (*UserTaskStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *UserTaskStatsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Запрос на статистику по команде
type TeamTaskStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        string                 `protobuf:"bytes,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamTaskStatsRequest) Reset() {
	*x = TeamTaskStatsRequest{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamTaskStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamTaskStatsRequest) ProtoMessage() {}

func (x *TeamTaskStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamTaskStatsRequest.ProtoReflect.Descriptor instead.
func (*TeamTaskStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TeamTaskStatsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

// Ответ со статистикой задач
type TaskStatsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalTasks      int32                  `protobuf:"varint,1,opt,name=total_tasks,json=totalTasks,proto3" json:"total_tasks,omitempty"`                  // Всего задач
	CompletedTasks  int32                  `protobuf:"varint,2,opt,name=completed_tasks,json=completedTasks,proto3" json:"completed_tasks,omitempty"`      // Выполнено
	InProgressTasks int32                  `protobuf:"varint,3,opt,name=in_progress_tasks,json=inProgressTasks,proto3" json:"in_progress_tasks,omitempty"` // В процессе (не выполнено, не просрочено)
	OverdueTasks    int32                  `protobuf:"varint,4,opt,name=overdue_tasks,json=overdueTasks,proto3" json:"overdue_tasks,omitempty"`            // Просрочено
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskStatsResponse) Reset() {
	*x = TaskStatsResponse{}
	mi := &file_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStatsResponse) ProtoMessage() {}

func (x *TaskStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStatsResponse.ProtoReflect.Descriptor instead.
func (*TaskStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *TaskStatsResponse) GetTotalTasks() int32 {
	if x != nil {
		return x.TotalTasks
	}
	return 0
}

func (x *TaskStatsResponse) GetCompletedTasks() int32 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

func (x *TaskStatsResponse) GetInProgressTasks() int32 {
	if x != nil {
		return x.InProgressTasks
	}
	return 0
}

func (x *TaskStatsResponse) GetOverdueTasks() int32 {
	if x != nil {
		return x.OverdueTasks
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\x1a\x1bgoogle/protobuf/empty.proto\"/\n" +
	"\x14UserTaskStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"/\n" +
	"\x14TeamTaskStatsRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\tR\x06teamId\"\xae\x01\n" +
	"\x11TaskStatsResponse\x12\x1f\n" +
	"\vtotal_tasks\x18\x01 \x01(\x05R\n" +
	"totalTasks\x12'\n" +
	"\x0fcompleted_tasks\x18\x02 \x01(\x05R\x0ecompletedTasks\x12*\n" +
	"\x11in_progress_tasks\x18\x03 \x01(\x05R\x0finProgressTasks\x12#\n" +
	"\roverdue_tasks\x18\x04 \x01(\x05R\foverdueTasks2\xb8\x01\n" +
	"\x10AnalyticsService\x12Q\n" +
	"\x10GetUserTaskStats\x12\x1f.analytics.UserTaskStatsRequest\x1a\x1c.analytics.TaskStatsResponse\x12Q\n" +
	"\x10GetTeamTaskStats\x12\x1f.analytics.TeamTaskStatsRequest\x1a\x1c.analytics.TaskStatsResponseB(Z&analytics/internal/delivery/grpc/pb;pbb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_analytics_proto_goTypes = []any{
	(*UserTaskStatsRequest)(nil), // 0: analytics.UserTaskStatsRequest
	(*TeamTaskStatsRequest)(nil), // 1: analytics.TeamTaskStatsRequest
	(*TaskStatsResponse)(nil),    // 2: analytics.TaskStatsResponse
}
var file_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.AnalyticsService.GetUserTaskStats:input_type -> analytics.UserTaskStatsRequest
	1, // 1: analytics.AnalyticsService.GetTeamTaskStats:input_type -> analytics.TeamTaskStatsRequest
	2, // 2: analytics.AnalyticsService.GetUserTaskStats:output_type -> analytics.TaskStatsResponse
	2, // 3: analytics.AnalyticsService.GetTeamTaskStats:output_type -> analytics.TaskStatsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
