volumes:
    task_db_volume:
services:
    gateway:
        container_name: gateway
        build: Gateway
        ports:
            - "8000:8000"
        restart: unless-stopped
    
    user:
        container_name: user
        build: User
        depends_on: []
        restart: unless-stopped
    
    task:
        container_name: task
        build: Task
        ports:
            - "8080:8080" # remove after testing
        depends_on: ["task_db"]
        restart: unless-stopped
    task_db:
        container_name: task_db
        build: PostgreSQL
        environment:
            - POSTGRES_DB=tasks
        volumes:
            - task_db_volume:/db
        restart: unless-stopped
    
    notification:
        container_name: notification
        build: Notification
        depends_on: []
        restart: unless-stopped

    analytics:
        container_name: analytics
        build: analytics
        ports:  # remove after testing
            - "8000:8000"
        depends_on: ["analytics_db"]
        restart: unless-stopped
    analytics_db:
        container_name: analytics_db
        build: Mongo
        restart: unless-stopped

    team:
        container_name: team
        build: Collaboration
        depends_on: ["team_db"]
        restart: unless-stopped
    team_db:
        container_name: team_db
        build: Mongo
        restart: unless-stopped