volumes:

services:
    gateway:
        container_name: gateway
        build: Gateway
        ports:
            - "8080:8080"
        restart: unless-stopped
    
    user:
        container_name: user
        build: User
        depends_on:
        restart: unless-stopped
    
    task:
        container_name: task
        build: Task
        depends_on:
        restart: unless-stopped
    
    notification:
        container_name: notification
        build: Notification
        depends_on:
        restart: unless-stopped

    analytics:
        container_name: analytics
        build: Analytics
        depends_on:
        restart: unless-stopped

    collaboration:
        container_name: collaboration
        build: Collaboration
        depends_on:
        restart: unless-stopped